doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either    here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Orm/Mapping'
                prefix: 'App\Orm\Entity'
                alias: App
            
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Adapter/Database/Orm/Doctrine/Mapping'
                prefix: 'User\Adapter\Database\Orm\Doctrine\Mapping'
                alias: User

            Group:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Group/Adapter/Database/Orm/Doctrine/Mapping'
                prefix: 'Group\Adapter\Database\Orm\Doctrine\Mapping'
                alias: Group

            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Order/Adapter/Database/Orm/Doctrine/Mapping'
                prefix: 'Order\Adapter\Database\Orm\Doctrine\Mapping'
                alias: Order

            Product:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Product/Adapter/Database/Orm/Doctrine/Mapping'
                prefix: 'Product\Adapter\Database\Orm\Doctrine\Mapping'
                alias: Product

            Shop:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shop/Adapter/Database/Orm/Doctrine/Mapping'
                prefix: 'Shop\Adapter\Database\Orm\Doctrine\Mapping'
                alias: Shop

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
