# -------------------------------------------------------------
# SHOP CREATE

shop_create:
  path: /api/v{api_version}/shops
  methods: POST
  controller: Shop\Adapter\Http\Controller\ShopCreate\ShopCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# SHOP MODIFY
# -------------------------------------------------------------
shop_modify:
  path: /api/v{api_version}/shops
  methods: PUT
  controller: Shop\Adapter\Http\Controller\ShopModify\ShopModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# SHOP REMOVE
# -------------------------------------------------------------
shop_remove:
  path: /api/v{api_version}/shops
  methods: DELETE
  controller: Shop\Adapter\Http\Controller\ShopRemove\ShopRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# SHOP GET DATA
# -------------------------------------------------------------
shop_get_data:
  path: /api/v{api_version}/shops
  methods: GET
  controller: Shop\Adapter\Http\Controller\ShopGetData\ShopGetDataController
  requirements:
    api_version: '\d+[.\d]?'
