# -------------------------------------------------------------
# PRODUCT CREATE
product_create:
  path: /api/v{api_version}/products
  methods: POST
  controller: Product\Adapter\Http\Controller\ProductCreate\ProductCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT MODIFY
# -------------------------------------------------------------
product_modify:
  path: /api/v{api_version}/products
  methods: PUT
  controller: Product\Adapter\Http\Controller\ProductModify\ProductModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT REMOVE
# -------------------------------------------------------------
product_remove:
  path: /api/v{api_version}/products
  methods: DELETE
  controller: Product\Adapter\Http\Controller\ProductRemove\ProductRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT REMOVE ALL GROUPS PRODUCTS
# -------------------------------------------------------------
product_remove_groups_products:
  path: /api/v{api_version}/products/group/remove-products
  methods: DELETE
  controller: Product\Adapter\Http\Controller\ProductRemoveAllGroupsProducts\ProductRemoveAllGroupsProductsController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT GET DATA
# -------------------------------------------------------------
product_get_data:
  path: /api/v{api_version}/products
  methods: GET
  controller: Product\Adapter\Http\Controller\ProductGetData\ProductGetDataController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT SET PRICE
# -------------------------------------------------------------
product_set_price:
  path: /api/v{api_version}/products/price
  methods: PUT
  controller: Product\Adapter\Http\Controller\SetProductShopPrice\SetProductShopPriceController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# PRODUCT GET PRICE
# -------------------------------------------------------------
product_get_price:
  path: /api/v{api_version}/products/price
  methods: GET
  controller: Product\Adapter\Http\Controller\GetProductShopPrice\GetProductShopPriceController
  requirements:
    api_version: '\d+[.\d]?'
